export const defaultSamples = [
  { type: "sound", key: 1, tempo: 3, level: 1, index: 1 },
  { type: "sound", key: 1, tempo: 2, level: 1, index: 2 },
  { type: "bass", key: 2, tempo: 2, level: 1, index: 1 },
  { type: "bass", key: 1, tempo: 2, level: 1, index: 2 },
  { type: "bass", key: 1, tempo: 1, level: 1, index: 3 },
  { type: "bass", key: 1, tempo: 3, level: 4, index: 8 },
  { type: "sound", key: 2, tempo: 2, level: 1, index: 3 },
  { type: "sound", key: 3, tempo: 2, level: 1, index: 4 },
  { type: "sound", key: 2, tempo: 2, level: 1, index: 5 },
  { type: "bass", key: 2, tempo: 2, level: 1, index: 5 },
  { type: "bass", key: 2, tempo: 3, level: 3, index: 4 },
  { type: "bass", key: 2, tempo: 1, level: 4, index: 7 },
  { type: "drum", level: 1, index: 1 },
  { type: "sound", key: 1, tempo: 2, level: 1, index: 6 },
  { type: "sound", key: 2, tempo: 1, level: 1, index: 7 },
  { type: "sound", key: 2, tempo: 3, level: 2, index: 8 },
  { type: "bass", key: 3, tempo: 2, level: 3, index: 6 },
  { type: "bass", key: 3, tempo: 1, level: 4, index: 9 },
  { type: "drum", level: 1, index: 2 },
  { type: "drum", level: 1, index: 3 },
  { type: "sound", key: 2, tempo: 3, level: 2, index: 9 },
  { type: "sound", key: 2, tempo: 3, level: 2, index: 10 },
  { type: "sound", key: 1, tempo: 1, level: 3, index: 11 },
  { type: "bass", key: 1, tempo: 3, level: 4, index: 10 },
  { type: "drum", level: 1, index: 4 },
  { type: "drum", level: 2, index: 5 },
  { type: "drum", level: 2, index: 6 },
  { type: "sound", key: 1, tempo: 1, level: 3, index: 12 },
  { type: "sound", key: 2, tempo: 2, level: 4, index: 13 },
  { type: "sound", key: 3, tempo: 2, level: 4, index: 14 },
  { type: "drum", level: 4, index: 7 },
  { type: "drum", level: 4, index: 8 },
  { type: "drum", level: 4, index: 9 },
  { type: "drum", level: 4, index: 10 },
  { type: "sound", key: 2, tempo: 2, level: 4, index: 15 },
  { type: "sound", key: 3, tempo: 2, level: 4, index: 16 }
];