import { GridButtonState } from "./constants";

export const defaultSong = [
  { id: "1", type: "sound", key: 1, tempo: 3, level: 1, index: 1, state: GridButtonState.default },
  { id: "2", type: "sound", key: 1, tempo: 2, level: 1, index: 2, state: GridButtonState.default },
  { id: "3", type: "bass", key: 2, tempo: 2, level: 1, index: 1, state: GridButtonState.default },
  { id: "4", type: "bass", key: 1, tempo: 2, level: 1, index: 2, state: GridButtonState.default },
  { id: "5", type: "bass", key: 1, tempo: 1, level: 1, index: 3, state: GridButtonState.default },
  { id: "6", type: "bass", key: 1, tempo: 3, level: 4, index: 8, state: GridButtonState.default },
  { id: "7", type: "sound", key: 2, tempo: 2, level: 1, index: 3, state: GridButtonState.default },
  { id: "8", type: "sound", key: 3, tempo: 2, level: 1, index: 4, state: GridButtonState.default },
  { id: "9", type: "sound", key: 2, tempo: 2, level: 1, index: 5, state: GridButtonState.default },
  { id: "10", type: "bass", key: 2, tempo: 2, level: 1, index: 5, state: GridButtonState.default },
  { id: "11", type: "bass", key: 2, tempo: 3, level: 3, index: 4, state: GridButtonState.default },
  { id: "12", type: "bass", key: 2, tempo: 1, level: 4, index: 7, state: GridButtonState.default },
  { id: "13", type: "drum", level: 1, index: 1, state: GridButtonState.default },
  { id: "14", type: "sound", key: 1, tempo: 2, level: 1, index: 6, state: GridButtonState.default },
  { id: "15", type: "sound", key: 2, tempo: 1, level: 1, index: 7, state: GridButtonState.default },
  { id: "16", type: "sound", key: 2, tempo: 3, level: 2, index: 8, state: GridButtonState.default },
  { id: "17", type: "bass", key: 3, tempo: 2, level: 3, index: 6, state: GridButtonState.default },
  { id: "18", type: "bass", key: 3, tempo: 1, level: 4, index: 9, state: GridButtonState.default },
  { id: "19", type: "drum", level: 1, index: 2, state: GridButtonState.default },
  { id: "20", type: "drum", level: 1, index: 3, state: GridButtonState.default },
  { id: "21", type: "sound", key: 2, tempo: 3, level: 2, index: 9, state: GridButtonState.default },
  { id: "22", type: "sound", key: 2, tempo: 3, level: 2, index: 10, state: GridButtonState.default },
  { id: "23", type: "sound", key: 1, tempo: 1, level: 3, index: 11, state: GridButtonState.default },
  { id: "24", type: "bass", key: 1, tempo: 3, level: 4, index: 10, state: GridButtonState.default },
  { id: "25", type: "drum", level: 1, index: 4, state: GridButtonState.default },
  { id: "26", type: "drum", level: 2, index: 5, state: GridButtonState.default },
  { id: "27", type: "drum", level: 2, index: 6, state: GridButtonState.default },
  { id: "28", type: "sound", key: 1, tempo: 1, level: 3, index: 12, state: GridButtonState.default },
  { id: "29", type: "sound", key: 2, tempo: 2, level: 4, index: 13, state: GridButtonState.default },
  { id: "30", type: "sound", key: 3, tempo: 2, level: 4, index: 14, state: GridButtonState.default },
  { id: "31", type: "drum", level: 4, index: 7, state: GridButtonState.default },
  { id: "32", type: "drum", level: 4, index: 8, state: GridButtonState.default },
  { id: "33", type: "drum", level: 4, index: 9, state: GridButtonState.default },
  { id: "34", type: "drum", level: 4, index: 10, state: GridButtonState.default },
  { id: "35", type: "sound", key: 2, tempo: 2, level: 4, index: 15, state: GridButtonState.default },
  { id: "36", type: "sound", key: 3, tempo: 2, level: 4, index: 16, state: GridButtonState.default }
];